In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("In-Person Voting.csv")
del df["Unnamed: 18"]
del df["Unnamed: 19"]

In [3]:
new_df=df[df["Date"] == "11/2/20"]

In [4]:
new_df=new_df.drop(["All Ballots RETURNED - Daily", "All In-Person - Daily", "DEM In-Person - Daily","REP In-Person - Daily", "Date"], axis=1)

In [5]:
new_df

,County,All Portal Applications,All Ballots SENT,All Ballots RETURNED,All In-Person,DEM Portal Applications,DEM Ballots SENT,DEM Ballots RETURNED,DEM In-Person,REP Portal Applications,REP Ballots SENT,REP Ballots RETURNED,REP In-Person
15,ADAIR,1304,1303,1244.0,6053.0,526,526,506.0,1046.0,707,707,673.0,4774.0
31,ALLEN,1518,1518,1419.0,5087.0,686,686,644.0,1095.0,747,747,703.0,3785.0
47,ANDERSON,2598,2597,2434.0,8782.0,1761,1760,1661.0,3620.0,714,714,663.0,4737.0
63,BALLARD,854,854,793.0,2731.0,659,659,617.0,1545.0,169,169,151.0,1096.0
79,BARREN,4505,4501,4110.0,11809.0,2914,2912,2681.0,4400.0,1387,1385,1260.0,6898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1855,WAYNE,2047,2043,1924.0,4557.0,823,823,774.0,859.0,1144,1140,1084.0,3568.0
1871,WEBSTER,897,897,845.0,3204.0,712,712,675.0,1904.0,151,151,138.0,1192.0
1887,WHITLEY,2761,2760,2515.0,10023.0,979,979,882.0,1115.0,1652,1652,1518.0,8540.0
1903,WOLFE,651,651,570.0,1425.0,550,550,491.0,1127.0,86,86,67.0,277.0
1919,WOODFORD,6283,6270,5777.0,7229.0,4331,4324,4020.0,2877.0,1579,1574,1436.0,3838.0

In [6]:
new_df["total_ballots"] = new_df["All Ballots RETURNED"] + new_df["All In-Person"]
new_df["total_dem_ballots"] = new_df["DEM Ballots RETURNED"]+new_df["DEM In-Person"]
new_df["total_rep_ballots"] = new_df["REP Ballots RETURNED"]+new_df["REP In-Person"]

new_df

,County,All Portal Applications,All Ballots SENT,All Ballots RETURNED,All In-Person,DEM Portal Applications,DEM Ballots SENT,DEM Ballots RETURNED,DEM In-Person,REP Portal Applications,REP Ballots SENT,REP Ballots RETURNED,REP In-Person,total_ballots,total_dem_ballots,total_rep_ballots
15,ADAIR,1304,1303,1244.0,6053.0,526,526,506.0,1046.0,707,707,673.0,4774.0,7297.0,1552.0,5447.0
31,ALLEN,1518,1518,1419.0,5087.0,686,686,644.0,1095.0,747,747,703.0,3785.0,6506.0,1739.0,4488.0
47,ANDERSON,2598,2597,2434.0,8782.0,1761,1760,1661.0,3620.0,714,714,663.0,4737.0,11216.0,5281.0,5400.0
63,BALLARD,854,854,793.0,2731.0,659,659,617.0,1545.0,169,169,151.0,1096.0,3524.0,2162.0,1247.0
79,BARREN,4505,4501,4110.0,11809.0,2914,2912,2681.0,4400.0,1387,1385,1260.0,6898.0,15919.0,7081.0,8158.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1855,WAYNE,2047,2043,1924.0,4557.0,823,823,774.0,859.0,1144,1140,1084.0,3568.0,6481.0,1633.0,4652.0
1871,WEBSTER,897,897,845.0,3204.0,712,712,675.0,1904.0,151,151,138.0,1192.0,4049.0,2579.0,1330.0
1887,WHITLEY,2761,2760,2515.0,10023.0,979,979,882.0,1115.0,1652,1652,1518.0,8540.0,12538.0,1997.0,10058.0
1903,WOLFE,651,651,570.0,1425.0,550,550,491.0,1127.0,86,86,67.0,277.0,1995.0,1618.0,344.0
1919,WOODFORD,6283,6270,5777.0,7229.0,4331,4324,4020.0,2877.0,1579,1574,1436.0,3838.0,13006.0,6897.0,5274.0

In [7]:
# In Person percentages

new_df["dems_in_person_pct"] = new_df["DEM In-Person"] *100/ new_df["total_dem_ballots"]
new_df["dems_in_person_pct"] =new_df["dems_in_person_pct"].round()

new_df["rep_in_person_pct"] = new_df["REP In-Person"] *100/ new_df["total_rep_ballots"]
new_df["rep_in_person_pct"] =new_df["rep_in_person_pct"].round()

In [8]:
# ballots returned

new_df["ballotsReturned_total_pct"] = new_df["All Ballots RETURNED"] *100/new_df["All Ballots SENT"]
new_df["ballotsReturned_total_pct"] = new_df["ballotsReturned_total_pct"].round()

new_df["ballotsReturned_dem_pct"] = new_df["DEM Ballots RETURNED"] *100/new_df["DEM Ballots SENT"]
new_df["ballotsReturned_dem_pct"] = new_df["ballotsReturned_dem_pct"].round()

new_df["ballotsReturned_rep_pct"] = new_df["REP Ballots RETURNED"] *100/new_df["REP Ballots SENT"]
new_df["ballotsReturned_rep_pct"] = new_df["ballotsReturned_rep_pct"].round()

In [9]:
filtered_df=new_df[["County",'total_ballots', 'total_dem_ballots',
       'total_rep_ballots', 'dems_in_person_pct', 'rep_in_person_pct',
       'ballotsReturned_total_pct', 'ballotsReturned_dem_pct',
       'ballotsReturned_rep_pct']].reset_index(drop=True)

In [10]:
filtered_df.head()

,County,total_ballots,total_dem_ballots,total_rep_ballots,dems_in_person_pct,rep_in_person_pct,ballotsReturned_total_pct,ballotsReturned_dem_pct,ballotsReturned_rep_pct
0,ADAIR,7297.0,1552.0,5447.0,67.0,88.0,95.0,96.0,95.0
1,ALLEN,6506.0,1739.0,4488.0,63.0,84.0,93.0,94.0,94.0
2,ANDERSON,11216.0,5281.0,5400.0,69.0,88.0,94.0,94.0,93.0
3,BALLARD,3524.0,2162.0,1247.0,71.0,88.0,93.0,94.0,89.0
4,BARREN,15919.0,7081.0,8158.0,62.0,85.0,91.0,92.0,91.0

In [11]:
#import voter registration data
voter_reg =pd.read_csv("voter_registration.csv")

voter_reg["non_party"] = voter_reg["Other"] + voter_reg["Ind"] + voter_reg["Libert"] + voter_reg["Green"]+ voter_reg["Const"] + voter_reg["Reform"] + voter_reg["Soc Wk"] 

voter_reg = voter_reg[["County", 'Dem', 'Rep', "non_party", "Registered"]]

In [12]:
merged_df = pd.merge(filtered_df, voter_reg, left_on="County", right_on="County")

In [13]:
merged_df["early_vote_registered_pct"] = (merged_df["total_ballots"]*100/merged_df["Registered"]).round()
merged_df["early_voter_dem_registered_pct"] = (merged_df["total_dem_ballots"]*100/merged_df["Dem"]).round()
merged_df["early_voter_rep_registered_pct"] = (merged_df["total_rep_ballots"]*100/merged_df["Rep"]).round()

In [16]:
merged_df.head()

,County,total_ballots,total_dem_ballots,total_rep_ballots,dems_in_person_pct,rep_in_person_pct,ballotsReturned_total_pct,ballotsReturned_dem_pct,ballotsReturned_rep_pct,Dem,Rep,non_party,Registered,early_vote_registered_pct,early_voter_dem_registered_pct,early_voter_rep_registered_pct
0,ADAIR,7297.0,1552.0,5447.0,67.0,88.0,95.0,96.0,95.0,3306,9862,863,14031,52.0,47.0,55.0
1,ALLEN,6506.0,1739.0,4488.0,63.0,84.0,93.0,94.0,94.0,4490,10065,1224,15779,41.0,39.0,45.0
2,ANDERSON,11216.0,5281.0,5400.0,69.0,88.0,94.0,94.0,93.0,8650,8848,1381,18879,59.0,61.0,61.0
3,BALLARD,3524.0,2162.0,1247.0,71.0,88.0,93.0,94.0,89.0,3966,2285,376,6627,53.0,55.0,55.0
4,BARREN,15919.0,7081.0,8158.0,62.0,85.0,91.0,92.0,91.0,14878,15543,2332,32753,49.0,48.0,52.0

In [18]:
merged_df.total_ballots.sum()/merged_df.Registered.sum()

0.45302723824460905