In [66]:
import pandas as pd
import re

In [72]:
demo90=pd.read_csv("jefferson_ct90.csv")
demo20=pd.read_csv("jefferson_ct20.csv")

In [68]:
demo90['other_races_1990']=demo90.total_pop_1990-demo90.white_1990-demo90.black_1990-demo90.hisp_1990
demo90["pct_other_races_1990"]=(demo90.other_races_1990*100/demo90.total_pop_1990).round(2)

In [69]:
demo90.sort_values("pct_other_races_1990")

,gcode_1990,GEOCODE_1990,tract_name_1990,total_pop_1990,white_1990,black_1990,hisp_1990,pct_white_1990,pct_black_1990,pct_hisp_1990,other_races_1990,pct_other_races_1990
83,G2101110009101,21111009101,Tract 91.01,706,705,1,0,99.86,0.14,0.00,0,0.00
172,G21011100006,21111000600,Tract 6,1921,208,1707,4,10.83,88.86,0.21,2,0.10
176,G21011100002,21111000200,Tract 2,1861,1793,51,15,96.35,2.74,0.81,2,0.11
164,G21011100014,21111001400,Tract 14,4347,62,4275,5,1.43,98.34,0.12,5,0.12
165,G21011100013,21111001300,Tract 13,1227,5,1220,0,0.41,99.43,0.00,2,0.16
...,...,...,...,...,...,...,...,...,...,...,...,...
101,G21011100102,21111010200,Tract 102,693,612,62,0,88.31,8.95,0.00,19,2.74
80,G2101110010002,21111010002,Tract 100.02,8541,7856,402,46,91.98,4.71,0.54,237,2.77
68,G2101110010701,21111010701,Tract 107.01,4450,4140,102,70,93.03,2.29,1.57,138,3.10
136,G21011100053,21111005300,Tract 53,2489,1546,762,43,62.11,30.61,1.73,138,5.54
134,G21011100056,21111005600,Tract 56,4730,2951,1177,44,62.39,24.88,0.93,558,11.80

In [70]:
demo20['pct_other_races_combined']=demo20.pct_asian+demo20.pct_other_races+demo20.pct_multiracial

In [71]:
demo20=demo20[['GEOCODE', 'NAME', 'pct_hisp_lat', 'pct_white', 'pct_black', 'pct_other_races_combined']]

In [24]:
demo90=demo90[['gcode_1990', 'GEOCODE_1990', 'tract_name_1990', 'pct_white_1990',
       'pct_black_1990', 'pct_hisp_1990', 
       'pct_other_races_1990']]

In [27]:
# demo20.to_csv("cleaned_jefferson_ct20.csv", index=False)
# demo90.to_csv("cleaned_jefferson_ct90.csv", index=False)

In [172]:
demo20.head()

,GEOCODE,NAME,total_pop,hisp_latino,white_alone_nh,black_alone_nh,asian_alone_nh,multiracial,other_races,pct_hisp_lat,pct_white,pct_black,pct_asian,pct_other_races,pct_multiracial
0,21111000201,Census Tract 2.01,1392,36,854,415,2,65,20,2.59,61.35,29.81,0.14,1.44,4.67
1,21111000202,Census Tract 2.02,1141,7,794,288,1,39,12,0.61,69.59,25.24,0.09,1.05,3.42
2,21111000300,Census Tract 3,2437,50,1001,1243,3,129,11,2.05,41.08,51.01,0.12,0.45,5.29
3,21111000400,Census Tract 4,4360,54,923,3193,0,152,38,1.24,21.17,73.23,0.00,0.87,3.49
4,21111000600,Census Tract 6,1671,40,98,1461,2,54,16,2.39,5.86,87.43,0.12,0.96,3.23

In [83]:
import requests
# response=pd.read_json("https://census-prod.news-engineering.aws.wapo.pub/21111000201.json")

In [173]:
response=requests.get("https://census-prod.news-engineering.aws.wapo.pub/21111000400.json")

In [174]:
data=response.json()

In [175]:
data.keys()

dict_keys(['21111000400', '21111'])

## jefferson county data

column names

'county_fips':"county_fips90", 
'totpop':"totpop90", 
'hisp':"hisp90", 
'white':"white90", 
'black':"black90", 
'nativam':"nativam90",
'asianpi':"asianpi90", 
'multi':"multi90", 
'diverse':"diverse90"

'county_fips':"county_fips00", 
'totpop':"totpop00", 
'hisp':"hisp00", 
'white':"white00", 
'black':"black00", 
'nativam':"nativam00",
'asianpi':"asianpi00", 
'multi':"multi00", 
'diverse':"diverse00"

'county_fips':"county_fips10", 
'totpop':"totpop10", 
'hisp':"hisp10", 
'white':"white10", 
'black':"black10", 
'nativam':"nativam10",
'asianpi':"asianpi10", 
'multi':"multi10", 
'diverse':"diverse10"

'county_fips':"county_fips20", 
'totpop':"totpop20", 
'hisp':"hisp20", 
'white':"white20", 
'black':"black20", 
'nativam':"nativam20",
'asianpi':"asianpi20", 
'multi':"multi20", 
'diverse':"diverse20"

In [178]:
county_d=data['21111']
df90=pd.DataFrame(county_d['1990'], 
                  index=[0]).rename(columns={
                                            'totpop':"totpop90", 
                                             'hisp':"hisp90", 'white':"white90", 
                                             'black':"black90", 'nativam':"nativam90", 
                                             'asianpi':"asianpi90", 'multi':"multi90", 'diverse':"diverse90"})

df00=pd.DataFrame(county_d['2000'], index=[0]).rename(columns=
                                                      { 'totpop':"totpop00", 'hisp':"hisp00", 'white':"white00", 'black':"black00", 'nativam':"nativam00", 'asianpi':"asianpi00", 'multi':"multi00", 'diverse':"diverse00"})

df10=pd.DataFrame(county_d['2010'], index=[0]).rename(columns=
                                                      {'totpop':"totpop10", 'hisp':"hisp10", 
                                                       'white':"white10", 'black':"black10", 'nativam':"nativam10", 'asianpi':"asianpi10", 'multi':"multi10", 'diverse':"diverse10"})

df20=pd.DataFrame(county_d['2020'], index=[0]).rename(columns=
                                                      {'totpop':"totpop20", 'hisp':"hisp20", 'white':"white20", 'black':"black20", 'nativam':"nativam20", 'asianpi':"asianpi20", 'multi':"multi20", 'diverse':"diverse20"})

df90=df90[['county_fips', 'totpop90', 'hisp90', 'white90', 'black90',
       'nativam90', 'asianpi90', 'multi90', 'diverse90']]
df00=df00[['county_fips', 'totpop00', 'hisp00', 'white00', 'black00',
       'nativam00', 'asianpi00', 'multi00', 'diverse00']]
df10=df10[['county_fips', 'totpop10', 'hisp10', 'white10', 'black10',
       'nativam10', 'asianpi10', 'multi10', 'diverse10']]

df10_90=pd.merge(df10,pd.merge(df00, df90))
merged_df=pd.merge(df20,df10_90)
merged_df
# .to_csv("pop_21111.csv", index=False)

,id,geo_level,state_postal,county_fips,urban_class,geo_name,lat,lon,totpop20,hisp20,...,multi00,diverse00,totpop90,hisp90,white90,black90,nativam90,asianpi90,multi90,diverse90
0,4200,County,KY,21111,1,Jefferson County,38.189532,-85.657624,782969,59021,...,8716,0.381,664959,4267,541595,112902,971,4562,None,0.308

In [365]:
df=pd.read_csv("pop_21111.csv")

In [626]:
df.white20

0    490251
Name: white20, dtype: int64

In [367]:
df["pct_hisp20"]=(df.hisp20*100/df.totpop20).round()
df["pct_white20"]=(df.white20*100/df.totpop20).round()
df["pct_black20"]=(df.black20*100/df.totpop20).round()
df["pct_nativam20"]=(df.nativam20*100/df.totpop20).round()
df["pct_asianpi20"]=(df.asianpi20*100/df.totpop20).round()

df["pct_hisp10"]=(df.hisp10*100/df.totpop10).round()
df["pct_white10"]=(df.white10*100/df.totpop10).round()
df["pct_black10"]=(df.black10*100/df.totpop10).round()
df["pct_nativam10"]=(df.nativam10*100/df.totpop10).round()
df["pct_asianpi10"]=(df.asianpi10*100/df.totpop10).round()

df["pct_hisp00"]=(df.hisp00*100/df.totpop00).round()
df["pct_white00"]=(df.white00*100/df.totpop00).round()
df["pct_black00"]=(df.black00*100/df.totpop00).round()
df["pct_nativam00"]=(df.nativam00*100/df.totpop00).round()
df["pct_asianpi00"]=(df.asianpi00*100/df.totpop00).round()

df["pct_hisp90"]=(df.hisp90*100/df.totpop90).round()
df["pct_white90"]=(df.white90*100/df.totpop90).round()
df["pct_black90"]=(df.black90*100/df.totpop90).round()
df["pct_nativam90"]=(df.nativam90*100/df.totpop90).round()
df["pct_asianpi90"]=(df.asianpi90*100/df.totpop90).round()

df['diverse20']=df['diverse20']*100
df['diverse10']=df['diverse10']*100
df['diverse00']=df['diverse00']*100
df['diverse90']=df['diverse90']*100

In [661]:
df[['county_fips','geo_level','diverse20','diverse10','diverse00','diverse90', 'pct_hisp20',
       'pct_white20', 'pct_black20', 'pct_nativam20', 'pct_asianpi20',
       'pct_hisp10', 'pct_white10', 'pct_black10', 'pct_nativam10',
       'pct_asianpi10', 'pct_hisp00', 'pct_white00', 'pct_black00',
       'pct_nativam00', 'pct_asianpi00', 'pct_hisp90', 'pct_white90',
       'pct_black90', 'pct_nativam90', 'pct_asianpi90']]
# .to_csv("21111_pop_share.csv", index=False)

,county_fips,geo_level,diverse20,diverse10,diverse00,diverse90,pct_hisp20,pct_white20,pct_black20,pct_nativam20,...,pct_hisp00,pct_white00,pct_black00,pct_nativam00,pct_asianpi00,pct_hisp90,pct_white90,pct_black90,pct_nativam90,pct_asianpi90
0,21111,County,55.6,45.8,38.1,30.8,8.0,63.0,21.0,0.0,...,2.0,76.0,19.0,0.0,1.0,1.0,81.0,17.0,0.0,1.0

In [675]:
df.pct_white90

0    81.0
Name: pct_white90, dtype: float64

In [662]:
df["pct_chng_hisp"]=df.pct_hisp20-df.pct_hisp90 
df["pct_chng_white"]=df.pct_white20-df.pct_white90 
df["pct_chng_black"]=df.pct_black20-df.pct_black90 
df["pct_chng_nativam"]=df.pct_nativam20-df.pct_nativam90 
df["pct_chng_asianpi"]=df.pct_asianpi20-df.pct_asianpi90 
df['pct_chng_diverse']=df.diverse20-df.diverse90

df["pct_chng_hisp10"]=df.pct_hisp20-df.pct_hisp10 
df["pct_chng_white10"]=df.pct_white20-df.pct_white10 
df["pct_chng_black10"]=df.pct_black20-df.pct_black10 
df["pct_chng_nativam10"]=df.pct_nativam20-df.pct_nativam10 
df["pct_chng_asianpi10"]=df.pct_asianpi20-df.pct_asianpi10 
df['pct_chng_diverse10']=df.diverse20-df.diverse10

In [666]:
df[['pct_chng_hisp',
       'pct_chng_white', 'pct_chng_black', 'pct_chng_nativam',
       'pct_chng_asianpi', 'pct_chng_diverse', 'pct_chng_hisp10',
       'pct_chng_white10', 'pct_chng_black10', 'pct_chng_nativam10',
       'pct_chng_asianpi10', 'pct_chng_diverse10']]

,pct_chng_hisp,pct_chng_white,pct_chng_black,pct_chng_nativam,pct_chng_asianpi,pct_chng_diverse,pct_chng_hisp10,pct_chng_white10,pct_chng_black10,pct_chng_nativam10,pct_chng_asianpi10,pct_chng_diverse10
0,7.0,-18.0,4.0,0.0,3.0,24.8,4.0,-8.0,0.0,0.0,2.0,9.8

In [668]:
df['pop_chng_20']=(df.totpop20-df.totpop10)*100/df.totpop10
df['pop_chng_10']=(df.totpop10-df.totpop00)*100/df.totpop00
df['pop_chng_00']=(df.totpop00-df.totpop90)*100/df.totpop90
df['pop_chng_20_90']=(df.totpop20-df.totpop90)*100/df.totpop90

In [670]:
df[['pop_chng_20',
       'pop_chng_10', 'pop_chng_00', 'pop_chng_20_90']]

   pop_chng_20  pop_chng_10  pop_chng_00  pop_chng_20_90
0     5.649575     6.851563     4.304025       17.746959

In [690]:
df.pct_hisp20

0    8.0
Name: pct_hisp20, dtype: float64

In [693]:
df.pct_hisp20

0    8.0
Name: pct_hisp20, dtype: float64

In [687]:
df.multi00/df.totpop00

0    0.012567
dtype: float64

In [697]:
df.black20*100/357764.0

0    46.697544
Name: black20, dtype: float64

In [700]:
df.pct_white20

0    63.0
Name: pct_white20, dtype: float64

## Tract level data

In [179]:
data.keys()

dict_keys(['21111000400', '21111'])

In [324]:
# tract=21111000400

# link=f"https://census-prod.news-engineering.aws.wapo.pub/{tract}.json"
# response=requests.get(link)
# data=response.json() 

# tract_d=data['21111000400']

# tract90=pd.DataFrame(tract_d["1990"], index=[0])
# tract90["tract_id"]="21111000400"
# tract90=tract90.rename(columns={'totpop':"totpop90",'hisp':"hisp90",'white':"white90", 'black':"black90", 
#                                 'nativam':"nativam90",'asianpi':"asianpi90",'multi':"multi90",'diverse':"diverse90"})

# tract00=pd.DataFrame(tract_d["2000"], index=[0])
# tract00["tract_id"]="21111000400"
# tract00=tract00.rename(columns={'totpop':"totpop00", 'hisp':"hisp00", 'white':"white00", 'black':"black00", 
#                                 'nativam':"nativam00",'asianpi':"asianpi00",'multi':"multi00",'diverse':"diverse00"})

# tract10=pd.DataFrame(tract_d["2010"], index=[0])
# tract10["tract_id"]="21111000400"
# tract10=tract10.rename(columns={'totpop':"totpop10", 'hisp':"hisp10", 'white':"white10", 'black':"black10", 
#                                 'nativam':"nativam10",'asianpi':"asianpi10",'multi':"multi10",'diverse':"diverse10"})

# tract20=pd.DataFrame(tract_d["2020"], index=[0])
# tract20["tract_id"]="21111000400"
# tract20=tract20.rename(columns={'totpop':"totpop20", 'hisp':"hisp20", 'white':"white20", 'black':"black20", 
#                                 'nativam':"nativam20",'asianpi':"asianpi20",'multi':"multi20",'diverse':"diverse20"})

# tract90=tract90[['tract_id', 'totpop90', 'hisp90', 'white90', 'black90',
#        'nativam90', 'asianpi90', 'multi90', 'diverse90']]
# tract00=tract00[['tract_id', 'totpop00', 'hisp00', 'white00', 'black00',
#        'nativam00', 'asianpi00', 'multi00', 'diverse00']]
# tract10=tract10[['tract_id', 'totpop10', 'hisp10', 'white10', 'black10',
#        'nativam10', 'asianpi10', 'multi10', 'diverse10']]

# tract10_90=pd.merge(tract10,pd.merge(tract00, tract90))

# merged_tracts=pd.merge(tract20,tract10_90)
# merged_tracts

In [323]:
tracts=demo20.GEOCODE
tracts_df=[]

for tract in tracts:
    tract_count=tract_count+1
    link=f"https://census-prod.news-engineering.aws.wapo.pub/{tract}.json"
    response=requests.get(link)
    data=response.json() 
    tract_d=data[f'{tract}']

    tract90=pd.DataFrame(tract_d["1990"], index=[0])
    tract90["tract_id"]=f'{tract}'
    tract90=tract90.rename(columns={'totpop':"totpop90",'hisp':"hisp90",'white':"white90", 'black':"black90", 
                                    'nativam':"nativam90",'asianpi':"asianpi90",'multi':"multi90",'diverse':"diverse90"})

    tract00=pd.DataFrame(tract_d["2000"], index=[0])
    tract00["tract_id"]=f'{tract}'
    tract00=tract00.rename(columns={'totpop':"totpop00", 'hisp':"hisp00", 'white':"white00", 'black':"black00", 
                                    'nativam':"nativam00",'asianpi':"asianpi00",'multi':"multi00",'diverse':"diverse00"})

    tract10=pd.DataFrame(tract_d["2010"], index=[0])
    tract10["tract_id"]=f'{tract}'
    tract10=tract10.rename(columns={'totpop':"totpop10", 'hisp':"hisp10", 'white':"white10", 'black':"black10", 
                                    'nativam':"nativam10",'asianpi':"asianpi10",'multi':"multi10",'diverse':"diverse10"})

    tract20=pd.DataFrame(tract_d["2020"], index=[0])
    tract20["tract_id"]=f'{tract}'
    tract20=tract20.rename(columns={'totpop':"totpop20", 'hisp':"hisp20", 'white':"white20", 'black':"black20", 
                                    'nativam':"nativam20",'asianpi':"asianpi20",'multi':"multi20",'diverse':"diverse20"})

    tract90=tract90[['tract_id', 'totpop90', 'hisp90', 'white90', 'black90',
           'nativam90', 'asianpi90', 'multi90', 'diverse90']]
    tract00=tract00[['tract_id', 'totpop00', 'hisp00', 'white00', 'black00',
           'nativam00', 'asianpi00', 'multi00', 'diverse00']]
    tract10=tract10[['tract_id', 'totpop10', 'hisp10', 'white10', 'black10',
           'nativam10', 'asianpi10', 'multi10', 'diverse10']]

    tract10_90=pd.merge(tract10,pd.merge(tract00, tract90))

    merged_tracts=pd.merge(tract20,tract10_90)
    
    tracts_df.append(merged_tracts)
final_df=pd.DataFrame(pd.concat(tracts_df, ignore_index=True))

In [325]:
final_df=final_df[['tract_id','geo_name', 'totpop20', 'hisp20', 'white20', 'black20',
       'nativam20', 'asianpi20', 'multi20', 'diverse20', 
       'totpop10', 'hisp10', 'white10', 'black10', 'nativam10', 'asianpi10',
       'multi10', 'diverse10', 'totpop00', 'hisp00', 'white00', 'black00',
       'nativam00', 'asianpi00', 'multi00', 'diverse00', 'totpop90', 'hisp90',
       'white90', 'black90', 'nativam90', 'asianpi90', 'multi90', 'diverse90', 'lat', 'lon']]

In [650]:
final_df=pd.read_csv("tracts_timeseries_race.csv")

In [651]:
df_90_20=final_df[['tract_id','geo_name', 'totpop20', 'hisp20', 'white20', 'black20',
       'nativam20', 'asianpi20', 'multi20', 'diverse20', 
      'totpop90', 'hisp90','white90', 'black90', 'nativam90', 'asianpi90', 'multi90', 'diverse90']]

In [652]:
df_90_20["pct_hisp20"]=(df_90_20.hisp20*100/df_90_20.totpop20).round()
df_90_20["pct_white20"]=(df_90_20.white20*100/df_90_20.totpop20).round()
df_90_20["pct_black20"]=(df_90_20.black20*100/df_90_20.totpop20).round()
df_90_20["pct_nativam20"]=(df_90_20.nativam20*100/df_90_20.totpop20).round()
df_90_20["pct_asianpi20"]=(df_90_20.asianpi20*100/df_90_20.totpop20).round()

df_90_20["pct_hisp90"]=(df_90_20.hisp90*100/df_90_20.totpop90).round()
df_90_20["pct_white90"]=(df_90_20.white90*100/df_90_20.totpop90).round()
df_90_20["pct_black90"]=(df_90_20.black90*100/df_90_20.totpop90).round()
df_90_20["pct_nativam90"]=(df_90_20.nativam90*100/df_90_20.totpop90).round()
df_90_20["pct_asianpi90"]=(df_90_20.asianpi90*100/df_90_20.totpop90).round()

<ipython-input-652-2336fbdfe4cc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_hisp20"]=(df_90_20.hisp20*100/df_90_20.totpop20).round()
<ipython-input-652-2336fbdfe4cc>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_white20"]=(df_90_20.white20*100/df_90_20.totpop20).round()
<ipython-input-652-2336fbdfe4cc>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_black20"]=(df_90_20.black20*100/df_90_20.totpop20).round()
<ipython-input-652-2336fbdfe4cc>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_nativam20"]=(df_90_20.nativam20*100/df_90_20.totpop20).round()
<ipython-input-652-2336fbdfe4cc>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_asianpi20"]=(df_90_20.asianpi20*100/df_90_20.totpop20).round()
<ipython-input-652-2336fbdfe4cc>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_hisp90"]=(df_90_20.hisp90*100/df_90_20.totpop90).round()
<ipython-input-652-2336fbdfe4cc>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_white90"]=(df_90_20.white90*100/df_90_20.totpop90).round()
<ipython-input-652-2336fbdfe4cc>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_black90"]=(df_90_20.black90*100/df_90_20.totpop90).round()
<ipython-input-652-2336fbdfe4cc>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_nativam90"]=(df_90_20.nativam90*100/df_90_20.totpop90).round()
<ipython-input-652-2336fbdfe4cc>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_asianpi90"]=(df_90_20.asianpi90*100/df_90_20.totpop90).round()

In [653]:
df_90_20["pct_chng_hisp"]=df_90_20.pct_hisp20-df_90_20.pct_hisp90 
df_90_20["pct_chng_white"]=df_90_20.pct_white20-df_90_20.pct_white90 
df_90_20["pct_chng_black"]=df_90_20.pct_black20-df_90_20.pct_black90 
df_90_20["pct_chng_nativam"]=df_90_20.pct_nativam20-df_90_20.pct_nativam90 
df_90_20["pct_chng_asianpi"]=df_90_20.pct_asianpi20-df_90_20.pct_asianpi90 
df_90_20['pct_chng_diverse']=(df_90_20.diverse20-df_90_20.diverse90)*100

<ipython-input-653-d1da2c1c5241>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_chng_hisp"]=df_90_20.pct_hisp20-df_90_20.pct_hisp90
<ipython-input-653-d1da2c1c5241>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_chng_white"]=df_90_20.pct_white20-df_90_20.pct_white90
<ipython-input-653-d1da2c1c5241>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_chng_black"]=df_90_20.pct_black20-df_90_20.pct_black90
<ipython-input-653-d1da2c1c5241>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_chng_nativam"]=df_90_20.pct_nativam20-df_90_20.pct_nativam90
<ipython-input-653-d1da2c1c5241>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20["pct_chng_asianpi"]=df_90_20.pct_asianpi20-df_90_20.pct_asianpi90
<ipython-input-653-d1da2c1c5241>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20['pct_chng_diverse']=(df_90_20.diverse20-df_90_20.diverse90)*100

In [654]:
df_90_20['diverse20']=df_90_20['diverse20']*100
df_90_20['diverse90']=df_90_20['diverse90']*100

<ipython-input-654-4bdd6d850daf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20['diverse20']=df_90_20['diverse20']*100
<ipython-input-654-4bdd6d850daf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_90_20['diverse90']=df_90_20['diverse90']*100

In [648]:
filtered_df=df_90_20[['tract_id', 'geo_name', 'diverse20', 'diverse90',
       'pct_hisp20', 'pct_white20', 'pct_black20', 'pct_nativam20',
       'pct_asianpi20', 'pct_hisp90', 'pct_white90', 'pct_black90',
       'pct_nativam90', 'pct_asianpi90', 'pct_chng_hisp', 'pct_chng_white',
       'pct_chng_black', 'pct_chng_nativam', 'pct_chng_asianpi',
       'pct_chng_diverse']]

In [344]:
(filtered_df.pct_chng_white < 0).sum()

199

In [348]:
((df_90_20.white20-df_90_20.white90)>0).sum()

68

In [349]:
((df_90_20.black20-df_90_20.black90)>0).sum()

180

In [655]:
df_90_20[df_90_20.pct_white20 > 75].white20.sum()

228656

In [656]:
df_90_20[df_90_20.pct_black20 > 75].black20.sum()

36344

In [630]:
# filtered_df.to_csv("tracts_popshare.csv", index=False)
# 228656/490251 
# - half of white residents live in nabes that are more than 75% white
# 36344/167067 - A fifth of Black residents live in nabes that are more than 75% black

# a 55.6% chance that two random people in a nabe are from two different races, that has increased from a 30.8%

# 86/216 census tracts have a diversity index of 50 or more

0.21754146540010894

In [659]:
df_90_20[df_90_20.diverse90 > 50]

,tract_id,geo_name,totpop20,hisp20,white20,black20,nativam20,asianpi20,multi20,diverse20,...,pct_white90,pct_black90,pct_nativam90,pct_asianpi90,pct_chng_hisp,pct_chng_white,pct_chng_black,pct_chng_nativam,pct_chng_asianpi,pct_chng_diverse
36,21111004900,Census Tract 49,3941,191,1809,1610,10,192,110,61.7,...,44.0,53.0,0.0,1.0,4.0,2.0,-12.0,0.0,4.0,10.0
37,21111005000,Census Tract 50,1754,86,645,865,8,51,75,61.8,...,58.0,40.0,0.0,0.0,4.0,-21.0,9.0,0.0,3.0,11.5
40,21111005300,Census Tract 53,3541,198,2173,791,13,170,159,56.8,...,62.0,31.0,0.0,4.0,4.0,-1.0,-9.0,0.0,1.0,5.0
41,21111005600,Census Tract 56,3524,416,1120,1358,11,446,153,72.1,...,59.0,27.0,0.0,12.0,11.0,-27.0,12.0,0.0,1.0,15.4
43,21111005902,Census Tract 59.02,2875,113,1518,912,20,165,106,61.6,...,48.0,51.0,0.0,0.0,3.0,5.0,-19.0,1.0,6.0,10.1
126,21111011007,Census Tract 110.07,3639,488,952,1492,3,507,180,72.6,...,45.0,52.0,0.0,1.0,12.0,-19.0,-11.0,0.0,13.0,20.1
141,21111011301,Census Tract 113.01,2425,484,564,1226,5,25,104,65.0,...,43.0,55.0,0.0,1.0,20.0,-20.0,-4.0,0.0,0.0,14.2
209,21111012701,Census Tract 127.01,4284,279,1075,2708,8,9,173,53.3,...,45.0,54.0,0.0,0.0,7.0,-20.0,9.0,0.0,0.0,2.9

## Nabe analysis

In [585]:
nabe=pd.read_csv("nabe_tracts20.csv", dtype={"GEOID20":str})

In [586]:
nabe.dtypes

GEOID20    object
nabe_id     int64
NH_NAME    object
dtype: object

In [587]:
new_df=df_90_20[['tract_id', 'geo_name', 'totpop20', 'hisp20', 'white20', 'black20',
       'nativam20', 'asianpi20', 'multi20','totpop90', 'hisp90',
       'white90', 'black90', 'nativam90', 'asianpi90', 'multi90']]

In [588]:
nabe_df=pd.merge(new_df,nabe, left_on="tract_id", right_on="GEOID20", left_index=False, right_index=False)

In [596]:
g_nabe_df=nabe_df.groupby(["nabe_id","NH_NAME"]).sum().reset_index()

In [598]:
g_nabe_df["pct_hisp20"]=(g_nabe_df.hisp20*100/g_nabe_df.totpop20).round()
g_nabe_df["pct_white20"]=(g_nabe_df.white20*100/g_nabe_df.totpop20).round()
g_nabe_df["pct_black20"]=(g_nabe_df.black20*100/g_nabe_df.totpop20).round()
g_nabe_df["pct_nativam20"]=(g_nabe_df.nativam20*100/g_nabe_df.totpop20).round()
g_nabe_df["pct_asianpi20"]=(g_nabe_df.asianpi20*100/g_nabe_df.totpop20).round()

g_nabe_df["pct_hisp90"]=(g_nabe_df.hisp90*100/g_nabe_df.totpop90).round()
g_nabe_df["pct_white90"]=(g_nabe_df.white90*100/g_nabe_df.totpop90).round()
g_nabe_df["pct_black90"]=(g_nabe_df.black90*100/g_nabe_df.totpop90).round()
g_nabe_df["pct_nativam90"]=(g_nabe_df.nativam90*100/g_nabe_df.totpop90).round()
g_nabe_df["pct_asianpi90"]=(g_nabe_df.asianpi90*100/g_nabe_df.totpop90).round()

g_nabe_df["pct_chng_hisp"]=g_nabe_df.pct_hisp20-g_nabe_df.pct_hisp90 
g_nabe_df["pct_chng_white"]=g_nabe_df.pct_white20-g_nabe_df.pct_white90 
g_nabe_df["pct_chng_black"]=g_nabe_df.pct_black20-g_nabe_df.pct_black90 
g_nabe_df["pct_chng_nativam"]=g_nabe_df.pct_nativam20-g_nabe_df.pct_nativam90 
g_nabe_df["pct_chng_asianpi"]=g_nabe_df.pct_asianpi20-g_nabe_df.pct_asianpi90

In [603]:
g_nabe_df[['nabe_id', 'NH_NAME','pct_hisp20', 'pct_white20',
       'pct_black20', 'pct_nativam20', 'pct_asianpi20', 'pct_hisp90',
       'pct_white90', 'pct_black90', 'pct_nativam90', 'pct_asianpi90',
       'pct_chng_hisp', 'pct_chng_white', 'pct_chng_black', 'pct_chng_nativam',
       'pct_chng_asianpi']]
# .to_csv("nabe_popshare.csv", index=False)

,nabe_id,NH_NAME,pct_hisp20,pct_white20,pct_black20,pct_nativam20,pct_asianpi20,pct_hisp90,pct_white90,pct_black90,pct_nativam90,pct_asianpi90,pct_chng_hisp,pct_chng_white,pct_chng_black,pct_chng_nativam,pct_chng_asianpi
0,199,REMAINDER OF CITY,3.0,85.0,6.0,0.0,2.0,1.0,93.0,5.0,0.0,1.0,2.0,-8.0,1.0,0.0,1.0
1,253,PORTLAND,3.0,39.0,53.0,0.0,1.0,1.0,52.0,47.0,0.0,0.0,2.0,-13.0,6.0,0.0,1.0
2,362,SHAWNEE,2.0,5.0,88.0,0.0,0.0,0.0,4.0,95.0,0.0,0.0,2.0,1.0,-7.0,0.0,0.0
3,391,ALGONQUIN,7.0,33.0,53.0,0.0,1.0,1.0,70.0,29.0,0.0,0.0,6.0,-37.0,24.0,0.0,1.0
4,412,BROWNSBORO ZORN,10.0,61.0,21.0,0.0,2.0,1.0,79.0,19.0,0.0,1.0,9.0,-18.0,2.0,0.0,1.0
5,578,BON AIR,8.0,58.0,17.0,0.0,12.0,1.0,92.0,6.0,0.0,1.0,7.0,-34.0,11.0,0.0,11.0
6,613,BUTCHERTOWN,4.0,70.0,17.0,0.0,4.0,1.0,73.0,26.0,0.0,0.0,3.0,-3.0,-9.0,0.0,4.0
7,725,CRESCENT HILL,3.0,87.0,4.0,0.0,3.0,1.0,97.0,2.0,0.0,1.0,2.0,-10.0,2.0,0.0,2.0
8,796,BEECHMONT,13.0,50.0,20.0,0.0,10.0,1.0,94.0,5.0,0.0,0.0,12.0,-44.0,15.0,0.0,10.0
9,817,CENTRAL BUSINESS DISTRICT,3.0,22.0,69.0,0.0,1.0,1.0,20.0,78.0,0.0,1.0,2.0,2.0,-9.0,0.0,0.0
10,912,AUBURNDALE,8.0,60.0,22.0,0.0,4.0,1.0,93.0,5.0,0.0,0.0,7.0,-33.0,17.0,0.0,4.0
11,958,RUSSELL,1.0,12.0,83.0,0.0,0.0,1.0,5.0,93.0,0.0,0.0,0.0,7.0,-10.0,0.0,0.0
12,1139,IRISH HILL,4.0,84.0,4.0,0.0,2.0,1.0,97.0,2.0,0.0,1.0,3.0,-13.0,2.0,0.0,1.0
13,1457,ROCKCREEK LEXINGTON ROAD,4.0,86.0,4.0,0.0,2.0,1.0,98.0,1.0,0.0,0.0,3.0,-12.0,3.0,0.0,2.0
14,1521,CHICKASAW,2.0,5.0,89.0,0.0,0.0,0.0,3.0,97.0,0.0,0.0,2.0,2.0,-8.0,0.0,0.0
15,1650,PARKLAND,2.0,5.0,88.0,0.0,0.0,0.0,3.0,96.0,0.0,0.0,2.0,2.0,-8.0,0.0,0.0
16,1714,CALIFORNIA,4.0,46.0,42.0,0.0,2.0,1.0,63.0,35.0,0.0,0.0,3.0,-17.0,7.0,0.0,2.0
17,1820,CHEROKEE TRIANGLE,4.0,85.0,4.0,0.0,2.0,1.0,96.0,3.0,0.0,0.0,3.0,-11.0,1.0,0.0,2.0
18,1999,REMAINDER OF CITY,6.0,72.0,8.0,0.0,10.0,1.0,94.0,3.0,0.0,1.0,5.0,-22.0,5.0,0.0,9.0
19,2164,SMOKETOWN JACKSON,4.0,84.0,5.0,1.0,1.0,1.0,95.0,3.0,0.0,0.0,3.0,-11.0,2.0,1.0,1.0
20,2247,OLD LOUISVILLE,5.0,63.0,22.0,0.0,4.0,1.0,72.0,25.0,0.0,2.0,4.0,-9.0,-3.0,0.0,2.0
21,2319,CHEROKEE SENECA,3.0,89.0,3.0,0.0,1.0,1.0,98.0,1.0,0.0,0.0,2.0,-9.0,2.0,0.0,1.0
22,2710,BOWMAN,4.0,83.0,7.0,0.0,2.0,1.0,98.0,1.0,0.0,0.0,3.0,-15.0,6.0,0.0,2.0
23,2899,REMAINDER OF CITY,4.0,16.0,75.0,0.0,0.0,0.0,25.0,75.0,0.0,0.0,4.0,-9.0,0.0,0.0,0.0
24,2930,GERMANTOWN,3.0,85.0,6.0,1.0,1.0,0.0,98.0,1.0,0.0,0.0,3.0,-13.0,5.0,1.0,1.0
25,3049,PARK HILL,3.0,11.0,80.0,0.0,1.0,0.0,16.0,83.0,0.0,0.0,3.0,-5.0,-3.0,0.0,1.0
26,3263,SHELBY PARK,4.0,86.0,4.0,0.0,1.0,0.0,93.0,5.0,0.0,0.0,4.0,-7.0,-1.0,0.0,1.0
27,3448,PARK DUVALLE,2.0,12.0,80.0,0.0,0.0,1.0,26.0,73.0,0.0,0.0,1.0,-14.0,7.0,0.0,0.0
28,3638,HIKES POINT,8.0,67.0,15.0,0.0,4.0,1.0,94.0,5.0,0.0,1.0,7.0,-27.0,10.0,0.0,3.0
29,3737,HIGHLANDS DOUGLASS,3.0,90.0,1.0,0.0,1.0,0.0,98.0,1.0,0.0,1.0,3.0,-8.0,0.0,0.0,0.0
30,3826,DEER PARK,3.0,88.0,3.0,0.0,1.0,1.0,98.0,1.0,0.0,0.0,2.0,-10.0,2.0,0.0,1.0
31,4161,SCHNITZELBURG,2.0,89.0,4.0,0.0,1.0,1.0,98.0,1.0,0.0,0.0,1.0,-9.0,3.0,0.0,1.0
32,4399,REMAINDER OF CITY,8.0,71.0,15.0,0.0,1.0,0.0,86.0,13.0,0.0,1.0,8.0,-15.0,2.0,0.0,0.0
33,4571,UNIVERSITY,11.0,60.0,22.0,0.0,1.0,0.0,95.0,3.0,1.0,1.0,11.0,-35.0,19.0,-1.0,0.0
34,4752,POPLAR LEVEL,4.0,85.0,5.0,0.0,1.0,0.0,99.0,0.0,0.0,1.0,4.0,-14.0,5.0,0.0,0.0
35,5232,HAWTHORNE,12.0,58.0,21.0,0.0,5.0,0.0,91.0,7.0,0.0,2.0,12.0,-33.0,14.0,0.0,3.0
36,5469,TAYLOR BERRY,11.0,47.0,35.0,0.0,1.0,1.0,90.0,9.0,0.0,0.0,10.0,-43.0,26.0,0.0,1.0
37,6029,GARDINER LANE,18.0,32.0,39.0,0.0,6.0,1.0,71.0,27.0,0.0,1.0,17.0,-39.0,12.0,0.0,5.0
38,6265,SOUTH LOUISVILLE,13.0,55.0,24.0,0.0,1.0,1.0,97.0,2.0,0.0,0.0,12.0,-42.0,22.0,0.0,1.0
39,6444,KLONDIKE,5.0,73.0,14.0,0.0,4.0,0.0,95.0,4.0,0.0,1.0,5.0,-22.0,10.0,0.0,3.0
40,6828,FAIRGROUNDS,7.0,50.0,7.0,0.0,0.0,0.0,91.0,8.0,0.0,0.0,7.0,-41.0,-1.0,0.0,0.0
41,7172,WILDER PARK,12.0,49.0,25.0,0.0,8.0,1.0,78.0,14.0,0.0,6.0,11.0,-29.0,11.0,0.0,2.0
42,7373,WYANDOTTE/OAKDALE,4.0,21.0,62.0,0.0,6.0,1.0,58.0,41.0,0.0,0.0,3.0,-37.0,21.0,0.0,6.0
43,7442,JACOBS,9.0,45.0,38.0,0.0,1.0,1.0,61.0,38.0,0.0,0.0,8.0,-16.0,0.0,0.0,1.0
44,7599,REMAINDER OF CITY,6.0,38.0,51.0,0.0,0.0,0.0,96.0,3.0,0.0,0.0,6.0,-58.0,48.0,0.0,0.0
45,7799,REMAINDER OF CITY,17.0,51.0,21.0,0.0,6.0,1.0,96.0,3.0,0.0,1.0,16.0,-45.0,18.0,0.0,5.0
46,8134,HAZELWOOD,10.0,56.0,23.0,0.0,6.0,1.0,96.0,3.0,0.0,1.0,9.0,-40.0,20.0,0.0,5.0
47,8467,SOUTHSIDE,15.0,55.0,20.0,0.0,5.0,1.0,98.0,1.0,0.0,0.0,14.0,-43.0,19.0,0.0,5.0
48,9043,KENWOOD HILL,14.0,56.0,17.0,0.0,9.0,0.0,97.0,2.0,0.0,1.0,14.0,-41.0,15.0,0.0,8.0

In [613]:
geo_df=gpd.read_file("GIS/geojson_files/nabe.geojson")

In [614]:
# geo_df["unqiue_id"]
geo_dfgeo_df.OBJECTID.astype(str)+geo_df.NH_CODE.astype(str)

0      199
1      253
2      362
3      412
4      523
      ...
87    8840
88    8966
89    9043
90     912
91    9299
Length: 92, dtype: object